college_api/urls.py
from django.urls import path

from college_api.views import *



app_name = "college_api" #custom  url

urlpatterns = [
    #parent api
    path('api/parent/list', ParentListCreate.as_view(), name='parent-create'),
    path('api/parent/update/delete/<int:id>/',ParentUpdateDetails.as_view(), name='parent-update'),

    #student api
    path('api/student/list', StudentListCreate.as_view(), name='student-create'),
    path('api/student/update/delete/<int:id>/', StudentUpdateDetails.as_view(), name='student-update'),

    #teacher api
    path('api/teacher/list', TeacherListCreate.as_view(), name='teacher-list'),
    path('api/teacher/update/delete/<int:id>/', TeacherUpdateDetails.as_view(), name='teacher-update')

]

college_management_app/urls.py
from django.urls import path
from college_management_app.views import (HomePage,RegisterPage, LoginPage, DashboardPage,StudentCreate, 
                                        LogoutPage, StudentList, StudentEdit, StudentDelete)

app_name = "college_management_app" #Custom url

urlpatterns = [
    path('', HomePage.as_view(), name='home-page'),
    path('dashboard/', DashboardPage.as_view(), name='dashboard-page'),
    path('register/', RegisterPage.as_view(), name='register-page'),
    path('login/', LoginPage.as_view(), name='login-page'),
    path('logout/', LogoutPage.as_view(), name='logout-page'),
    
    #student url
    path('student_create/',StudentCreate.as_view(), name='student-create'),
    path('student_list/', StudentList.as_view(), name='student-list'),
    path('student/<int:id>/update/', StudentEdit.as_view(), name='student-update'),
    path('student/<int:pk>/delete/', StudentDelete.as_view(), name='student-delete')
]

college_management_system/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),   
    path('', include('college_management_app.urls')),
    path('', include('college_api.urls')),
    # path('auth/', include('social_django.urls', namespace='social')),
    path('accounts/', include('allauth.urls')),
]

urlpatterns += static(settings.STATIC_URL, document_root = settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

college_management_app/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone
# Create your models here.

#making global variable for choices
GENDER = (
    ('MALE','MALE'),
    ('FEMALE','FEMALE'),
    ('OTHER','OTHER'),
)

FACULTY = (
    ('SCIENCE','SCIENCE'),
    ('MANAGEMENT','MANAGEMENT'),
    ('OTHER','OTHER')
)

class Parent(models.Model):
    name = models.CharField(max_length=100)
    gender = models.CharField(max_length=100, choices=GENDER)
    photo = models.ImageField(upload_to="parent/photo", null=True, blank=True)
    ph_number = models.PositiveIntegerField("Phone Number")
    deleted_at = models.DateTimeField(null=True, blank=True)

    class Meta:
        verbose_name = "Parent"
        verbose_name_plural = "Parents"

    def __str__(self):
        return "{}".format(self.name)

    def delete_at(self):
        self.deleted_at = timezone.now()
        super().save()

class Student(models.Model):
    name = models.CharField("Student Name",max_length=100)
    faculty = models.CharField(max_length=100, choices=FACULTY)
    address = models.CharField(max_length=100)
    email = models.EmailField(null=True, blank=True)
    ph_number = models.PositiveIntegerField("Phone Number")
    photo = models.ImageField(upload_to="student/photo",null=True, blank=True)
    age = models.PositiveIntegerField(null=True, blank=True)
    gender = models.CharField(max_length=100, choices=GENDER)
    date_created = models.DateTimeField(auto_now_add=True)
    deleted_at = models.DateTimeField(null=True, blank=True)

    class Meta:
        verbose_name = "Student"
        verbose_name_plural = "Students"

    def __str__(self):
        return "{}".format(self.name)

    def delete(self):
        self.deleted_at = timezone.now()
        super().save()


class Teacher(models.Model):
    name = models.CharField(max_length=100)
    student = models.ForeignKey(Student, on_delete=models.CASCADE, related_name="teachers")
    address = models.CharField(max_length=100)
    email = models.EmailField()
    ph_number = models.PositiveIntegerField("Phone Number")
    photo = models.ImageField(upload_to="teacher/photo",null=True, blank=True)
    age = models.PositiveIntegerField(null=True, blank=True)
    faculty = models.CharField(max_length=100, choices=FACULTY)
    gender = models.CharField(max_length=100, choices=GENDER)
    date_created = models.DateTimeField(auto_now_add=True)
    deleted_at = models.DateTimeField(null=True, blank=True)

    class Meta:
        verbose_name = "Teacher"
        verbose_name_plural = "Teachers"

    def __str__(self):
        return "{}".format(self.name)

    def delete_at(self):
        self.deleted_at = timezone.now()
        super().save()

class Accountant(models.Model):
    name = models.CharField(max_length=100)
    teacher = models.ForeignKey(Teacher, on_delete=models.CASCADE, related_name = "accountants")
    student = models.ForeignKey(Student, on_delete=models.CASCADE, related_name = "accountants")
    amount = models.PositiveIntegerField("Salary of teacher and amount to be paid by student")
    ph_number = models.PositiveIntegerField("Phone Number")
    date_created = models.DateTimeField(auto_now_add=True)
    deleted_at = models.DateTimeField(null=True, blank=True)

    class Meta:
        verbose_name = "Accountant"
        verbose_name_plural = "Accountants"

    def __str__(self):
        return "{}".format(self.name)

    def delete_at(self):
        self.deleted_at = timezone.now()
        super().save()


class Subject(models.Model):
    name = models.CharField(max_length=100)
    faculty = models.CharField(max_length=100, choices=FACULTY)
    student = models.ManyToManyField(Student, related_name="subjects")
    teacher = models.ManyToManyField(Teacher, related_name="subjects")
    date_created = models.DateTimeField(auto_now_add=True)
    deleted_at = models.DateTimeField(null=True, blank=True)

    class Meta:
        verbose_name = "Subject"
        verbose_name_plural = "Subjects"

    def __str__(self):
        return "{}".format(self.name)

    def delete(self):
        self.deleted_at = timezone.now()
        super().save()

class Admin(models.Model):
    name = models.OneToOneField(User, on_delete=models.CASCADE, related_name="admins")
    photo = models.ImageField(upload_to="admin/photo",null=True, blank=True)
    ph_number = models.PositiveIntegerField("Phone Number")
    gender = models.CharField(max_length=100, choices=GENDER)
    age = models.PositiveIntegerField(null=True, blank=True)
    email = models.EmailField(default="abc@gmail.com", null=True, blank=True)
    deleted_at = models.DateTimeField(null=True, blank=True)

    class Meta:
        verbose_name_plural = "Admins"

    def __str__(self):
        return "{}".format(self.name)

    def delete(self):
        self.deleted_at = timezone.now()
        super().save()


class Driver(models.Model):
    name = models.CharField("Driver Name", max_length=100)
    photo = models.ImageField(upload_to="driver/photo",null=True, blank=True)
    age = models.PositiveIntegerField() 
    ph_number = models.PositiveIntegerField("Phone number of driver who used bus")
    gender = models.CharField(max_length=100, choices=GENDER)
    deleted_at = models.DateTimeField(null=True, blank=True)

    class Meta:
        verbose_name = "Driver"
        verbose_name_plural = "Drivers"

    def __str__(self):
        return "{}".format(self.name)

    def delete_at(self):
        self.deleted_at = timezone.now()
        super().save()

college_management_app/forms.py
from msilib.schema import Error
from college_management_app.models import *

from django.contrib.auth.models import User
from django import forms


class RegisterForm(forms.Form):
    username = forms.CharField(widget=forms.TextInput())
    email = forms.CharField(widget=forms.EmailInput())
    password = forms.CharField(widget=forms.PasswordInput())
    confirm_password = forms.CharField(widget=forms.PasswordInput())


    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['username'].widget.attrs.update({
            'class':'form-control',
            'placeholder':'Enter your username'
        })
        for field in self.fields:
            self.fields[field].widget.attrs.update({
                'class':'form-control',
            })

    def clean_username(self):
        uname = self.cleaned_data['username']
        if User.objects.filter(username=uname).exists():
            raise forms.ValidationError('Username Already exists')
        return uname
    
    def clean_mail(self):
        email = self.cleaned_data['email']
        if User.objects.filter(email=email).exists():
            raise forms.ValidationError('Email Already exists')
        return email

    def clean_confirm_password(self):
        pwd = self.cleaned_data['password']
        cf_pwd = self.cleaned_data['confirm_password']

        if pwd != cf_pwd:
            raise forms.ValidationError("Password didn't match")
        return cf_pwd

class LoginForm(forms.Form):
    username = forms.CharField(widget=forms.TextInput())
    password = forms.CharField(widget=forms.PasswordInput())

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['username'].widget.attrs.update({
            'class':'form-control',
            'placeholder':'Enter your username'
        })
        self.fields['password'].widget.attrs.update({
            'class':'form-control',
            'placeholder':'Enter your password'
        })
        
    


class StudentForm(forms.ModelForm):
    class Meta:
        model = Student
        fields = ['name','faculty','address','ph_number','age','gender','photo']

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['name'].widget.attrs.update({
            'class':'form-control',
            'placeholder':'Enter your Name'
        })
        for field in self.fields:
            self.fields[field].widget.attrs.update({
                'class':'form-control',
            })
        self.fields['photo'].widget.attrs.update({
            'class':'form-control',
            'onchange':'loadFile(event)',
        })

    def clean_number(self):
        ph_number = self.cleaned_data['ph_number']
        if len(ph_number) < 10:
            raise forms.ValidationError('Please enter more than 10 number')
        return ph_number

college_management_app/views.py
from django.shortcuts import render, redirect
from django.views.generic import (TemplateView, FormView, CreateView, View, ListView, 
                                UpdateView, DeleteView, DetailView)
from django.urls import reverse_lazy
from django.contrib.messages.views import SuccessMessageMixin
from django.contrib.auth.models import User
from django.contrib.auth import authenticate, login, logout
from django.http import JsonResponse, QueryDict
from django.db.models import Q
from django.shortcuts import get_object_or_404

from college_management_app.filters import StudentFilter
from college_management_app.models import *
from college_management_app.forms import RegisterForm, LoginForm, StudentForm

#class based views

#Login required mixins
class LoginRequiredMixin(object):
    def dispatch(self, request, *args, **kwargs):
        user = self.request.user
        if user.is_authenticated:
            pass
        else:
            return redirect('college_management_app:login-page')
        return super().dispatch(request, *args, **kwargs)
    


class HomePage(TemplateView):
    template_name = "college/index.html"

class DashboardPage(LoginRequiredMixin,TemplateView):
    template_name = "dashboard/base.html"

class RegisterPage(SuccessMessageMixin,FormView):
    template_name = "registration/register.html"
    form_class = RegisterForm
    success_url = reverse_lazy('college_management_app:register-page')
    success_message = "Register Successfully"

    def form_valid(self, form):
        uname = form.cleaned_data['username']
        email = form.cleaned_data['email']
        pwd = form.cleaned_data['password']
        cf_pwd = form.cleaned_data['confirm_password']

        User.objects.create_user(username=uname, email=email, password=pwd)
        return super().form_valid(form)

    def get_success_message(self, cleaned_data):
        return self.success_message % cleaned_data

class LoginPage(FormView):
    template_name = "registration/login.html"
    form_class = LoginForm
    success_url = reverse_lazy('college_management_app:login-page')

    def form_valid(self, form):
        uname = form.cleaned_data['username']
        pword = form.cleaned_data['password']

        user = authenticate(username=uname, password=pword)

        if user is not None:
            login(self.request, user)
            print(user,'--------------')
            return redirect('college_management_app:dashboard-page')
        else:
            return render(self.request, self.template_name,{'error':'Username or Password is incorrect','form':form})

        return super().form_valid(form)


class LogoutPage(View):
    def get(self, request):
        logout(request)
        return redirect('college_management_app:login-page')


#Crud Student
class StudentList(ListView):
    template_name = 'student/list.html'
    model = Student
    context_object_name = 'student_list'
    paginate_by = 2

    #search query
    def get_queryset(self):
        query = self.request.GET.get('q')
        object_list = self.model.objects.all()
        if query:
            object_list = object_list.filter(name__icontains=query)
        return object_list


class StudentCreate(LoginRequiredMixin,SuccessMessageMixin,CreateView):
    template_name = "student/add.html"
    form_class = StudentForm
    success_url = reverse_lazy('college_management_app:student-create')
    success_message = "Student Register Successful"

    def form_valid(self, form):
        form.save()
        return super().form_valid(form)

    def get_success_message(self,cleaned_data):
        return self.success_message % cleaned_data

class StudentEdit(LoginRequiredMixin,SuccessMessageMixin,UpdateView):
    template_name = 'student/edit.html'
    form_class = StudentForm
    success_url = reverse_lazy('college_management_app:student-list')
    success_message = "Student Update Successful"


    def get_object(self, **kwargs):
        id = self.kwargs.get('id')
        return get_object_or_404(Student, id=id)

    def form_valid(self, form):
        form.save()
        return super().form_valid(form)

    def get_success_message(self, cleaned_data):
        return self.success_message % cleaned_data

class StudentDelete(LoginRequiredMixin,SuccessMessageMixin,DeleteView):
    template_name = 'student/delete.html'
    model = Student
    success_url = reverse_lazy("college_management_app:student-list")
    success_message = "Student information is deleted"

    def get_object(self, **kwargs):
        id = self.kwargs.get('id')
        return get_object_or_404(Student, id=id)

    def get_success_message(self, cleaned_data):
        return self.success_message % cleaned_data

college_management_app/templates/student/add.html
{% extends 'dashboard/base.html' %}
{% load crispy_forms_tags %}
{% block content %}

<script src="https://unpkg.com/sweetalert/dist/sweetalert.min.js"></script>
<form method="POST" action="" enctype="multipart/form-data">
    {% if messages %}
        {% for message in messages %}
            <div class="alert alert-primary" role="alert">
                {{ message }}
            </div>
        {% endfor %}
    {% endif %}
    {% csrf_token %}
    <div class="modal-header">
        <h4 class="title-header"> Add Student </h4>
    </div>

    <div class="modal-body">
        {{ form.non_field_errors }}
        {% for f in form %}
            <div class="form-group" required>
                <label> {{ f.label }} </label>
                {{ f }}
                <span> {{ f.errors|striptags }} </span>
            </div>
        {% endfor %}
        <img id="output_image"/ style="width:100px;" "height:100px;"> 
        <button type="submit" class="btn btn-primary"> Add Student </button>
    </div>
</form>
{% endblock content %}
{% block scripts %}
<script>
    $(document).ready(function(){
        $('#id_faculty').select2();
    })

    var loadFile = function(event){
        var reader = new FileReader();
        reader.onload = function(){
            var output = document.getElementById('output_image');
            output.src = reader.result;
        };
        reader.readAsDataURL(event.target.files[0]);
    };
</script>

{% endblock scripts %}

college_management_app/templates/student/delete.html
{% block content %}
<form method="POST" action="{% url 'college_management_app:student-delete' object.id %}">
    {% csrf_token %}
        <div class="modal-header">
            <h4 class="modal-title">Delete Student</h4>
            <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        </div>
        <div class="modal-body">
            <p>Are you sure you want to delete these Records?</p>
            <p class="text-warning"><small>{{ object.name }}: Information deleted </small></p>
        </div>
    <div class="modal-footer">
        <input type="button" class="btn btn-default" data-dismiss="modal" value="Cancel">
        <input type="submit" class="btn btn-success" value="Delete">
    </div>
</form>

{% endblock content %}

college_management_app/templates/student/edit.html
{% block content %}
<form method="POST" enctype="multipart/form-data" action="{% url 'college_management_app:student-update'  object.id %}"> 
    {% csrf_token %}
    <div class="modal-header">
        <h4 class="modal-title"> Student Update </h4>
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
    </div>
    <div class="modal-body">
        {% for f in form %}
        <div class="form-group">
            <label> {{ f }} </label> 
        </div>
        {% endfor %}
    </div>
    <div class="modal-footer">
        <input type="button" class="btn btn-default" data-dismiss="modal" value="Cancel">
        <input type="submit" class="btn btn-success" value="Edit">
    </div>
</form>
{% endblock content %}

college_management_app/templates/student/list.html
{% extends 'dashboard/base.html' %}
{% block content %}

<div class="container">
    <div class="row justify-content-start">
        <form class="search-form" method="GET">
            {% csrf_token %}
            <input type="text" name="q" placeholder="Enter your name">
            <button type="submit" class="btn btn-primary"> Search </button>
        </form>
    </div>
</div>

<div class="container">
    <div class="table-wrapper">
        <div class="table-title">
            <div class="row">
                <div class="col-sm-6">
                    <h2>Manage <b>Student</b></h2>
                    
                </div>
            </div>
        </div>
        <table class="table table-bordered">
            <thead>
                <tr>
                    <th>ID</th>
                    <th>Name</th>
                    <th>Address</th>
                    <th>Image</th>
                    <th>Action</th>
                </tr>
                {% for std in student_list %}
                <tr>
                    <td>{{ forloop.counter }}</td>
                    <td>{{ std.name }}</td>
                    <td>{{ std.address }}</td>
                    <td><img src="{{ std.photo.url }}" style="height:50px; width:50px;"><a href="{{ std.photo.url }}"></a></td>
                    <td>
                        <a href="{% url 'college_management_app:student-update' std.id %}" class="btn btn-info editbtn">Edit </a>
                        <a href="{% url 'college_management_app:student-delete' std.id %}" class="btn btn-danger deletebtn"> Delete </a>
                    </td>
                </tr>

                {% endfor %}
            </thead>
        </table>

        <!--Add pagination in Author-->
        <div class="container">
            <div class="row justify-content-end">
                <nav aria-label="Page navigation example">
                    {% if is_paginated %}
                    <ul class="pagination">
                        {% if page_obj.has_previous %}
                        <li class="page-item">
                            <a class="page-link" href="?page={{page_obj.previous_page_number}}">&laquo;</a>
                        </li>
                        {% else %}
                        <li class="page-item disabled">
                            <a class="page-link" href="#">&laquo;</a>
                        </li>
                        {% endif %} {% for i in paginator.page_range %} {% if page_obj.number == i %}
                        <li class="page-item"><a class="page-link active">{{ i }}</a></li>
                        {% else %}
                        <li class="page-item">
                            <a class="page-link" href="?page={{ i }}">{{ i }}</a>
                        </li>
                        {% endif %} {% endfor %} {% if page_obj.has_next %}
                        <li class="page-item">
                            <a href="?page={{page_obj.next_page_number}}" class="page-link">&raquo;</a>
                        </li>
                        {% else %}
                        <li class="page-item disabled">
                            <a class="page-link">&raquo;</a>
                        </li>
                        {% endif %}
                    </ul>
                    {% endif %}
                </nav>
            </div>
        </div>
        <!--Add Author-->

        <!-- Edit Author-->
        <div id="editStudentModal" class="modal fade" tabindex="-1" role="dialog" aria-labelledby="..."
            aria-hidden="true">
            <div class="modal-dialog">
                <div class="modal-content">
                </div>
            </div>
        </div>

        <!--Delete Author-->
        <div id="deleteStudentModal" class="modal fade" tabindex="-1" role="dialog" aria-labelledby="..."
            aria-hidden="true">
            <div class="modal-dialog">
                <div class="modal-content">
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock content %}

{% block scripts %}
<script>
    $('.editbtn').on('click', function (e) {
        e.preventDefault()
        var url = $(this).attr('href');
        $.get(url, function (data) {
            console.log(data)
            $('#editStudentModal').modal('show');
            $('#editStudentModal .modal-content').empty().append(data)
        })
    })

    $('.deletebtn').on('click', function (e) {
        e.preventDefault()
        var url = $(this).attr('href');
        $.get(url, function (data) {
            console.log(data)
            $('#deleteStudentModal').modal('show');
            $('#deleteStudentModal .modal-content').empty().append(data)
        })
    })
</script>
{% endblock scripts %}