college_api/urls.py
from django.urls import path

from college_api.views import *



app_name = "college_api" #custom  url

urlpatterns = [
    #parent api
    path('api/parent/list', ParentListCreate.as_view(), name='parent-create'),
    path('api/parent/update/delete/<int:id>/',ParentUpdateDetails.as_view(), name='parent-update'),

    #student api
    path('api/student/list', StudentListCreate.as_view(), name='student-create'),
    path('api/student/update/delete/<int:id>/', StudentUpdateDetails.as_view(), name='student-update'),

    #teacher api
    path('api/teacher/list', TeacherListCreate.as_view(), name='teacher-list'),
    path('api/teacher/update/delete/<int:id>/', TeacherUpdateDetails.as_view(), name='teacher-update')

]

college_management_app/urls.py
from django.urls import path
from college_management_app.views import (HomePage,RegisterPage, LoginPage, DashboardPage,StudentCreate, 
                                        LogoutPage, StudentList, StudentEdit, StudentDelete)

app_name = "college_management_app" #Custom url

urlpatterns = [
    path('', HomePage.as_view(), name='home-page'),
    path('dashboard/', DashboardPage.as_view(), name='dashboard-page'),
    path('register/', RegisterPage.as_view(), name='register-page'),
    path('login/', LoginPage.as_view(), name='login-page'),
    path('logout/', LogoutPage.as_view(), name='logout-page'),
    
    #student url
    path('student_create/',StudentCreate.as_view(), name='student-create'),
    path('student_list/', StudentList.as_view(), name='student-list'),
    path('student/<int:id>/update/', StudentEdit.as_view(), name='student-update'),
    path('student/<int:pk>/delete/', StudentDelete.as_view(), name='student-delete')
]

college_management_system/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),   
    path('', include('college_management_app.urls')),
    path('', include('college_api.urls')),
    # path('auth/', include('social_django.urls', namespace='social')),
    path('accounts/', include('allauth.urls')),
]

urlpatterns += static(settings.STATIC_URL, document_root = settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

college_management_app/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone
# Create your models here.

#making global variable for choices
GENDER = (
    ('MALE','MALE'),
    ('FEMALE','FEMALE'),
    ('OTHER','OTHER'),
)

FACULTY = (
    ('SCIENCE','SCIENCE'),
    ('MANAGEMENT','MANAGEMENT'),
    ('OTHER','OTHER')
)

class Parent(models.Model):
    name = models.CharField(max_length=100)
    gender = models.CharField(max_length=100, choices=GENDER)
    photo = models.ImageField(upload_to="parent/photo", null=True, blank=True)
    ph_number = models.PositiveIntegerField("Phone Number")
    deleted_at = models.DateTimeField(null=True, blank=True)

    class Meta:
        verbose_name = "Parent"
        verbose_name_plural = "Parents"

    def __str__(self):
        return "{}".format(self.name)

    def delete_at(self):
        self.deleted_at = timezone.now()
        super().save()

class Student(models.Model):
    name = models.CharField("Student Name",max_length=100)
    faculty = models.CharField(max_length=100, choices=FACULTY)
    address = models.CharField(max_length=100)
    email = models.EmailField(null=True, blank=True)
    ph_number = models.PositiveIntegerField("Phone Number")
    photo = models.ImageField(upload_to="student/photo",null=True, blank=True)
    age = models.PositiveIntegerField(null=True, blank=True)
    gender = models.CharField(max_length=100, choices=GENDER)
    date_created = models.DateTimeField(auto_now_add=True)
    deleted_at = models.DateTimeField(null=True, blank=True)

    class Meta:
        verbose_name = "Student"
        verbose_name_plural = "Students"

    def __str__(self):
        return "{}".format(self.name)

    def delete(self):
        self.deleted_at = timezone.now()
        super().save()


class Teacher(models.Model):
    name = models.CharField(max_length=100)
    student = models.ForeignKey(Student, on_delete=models.CASCADE, related_name="teachers")
    address = models.CharField(max_length=100)
    email = models.EmailField()
    ph_number = models.PositiveIntegerField("Phone Number")
    photo = models.ImageField(upload_to="teacher/photo",null=True, blank=True)
    age = models.PositiveIntegerField(null=True, blank=True)
    faculty = models.CharField(max_length=100, choices=FACULTY)
    gender = models.CharField(max_length=100, choices=GENDER)
    date_created = models.DateTimeField(auto_now_add=True)
    deleted_at = models.DateTimeField(null=True, blank=True)

    class Meta:
        verbose_name = "Teacher"
        verbose_name_plural = "Teachers"

    def __str__(self):
        return "{}".format(self.name)

    def delete_at(self):
        self.deleted_at = timezone.now()
        super().save()

class Accountant(models.Model):
    name = models.CharField(max_length=100)
    teacher = models.ForeignKey(Teacher, on_delete=models.CASCADE, related_name = "accountants")
    student = models.ForeignKey(Student, on_delete=models.CASCADE, related_name = "accountants")
    amount = models.PositiveIntegerField("Salary of teacher and amount to be paid by student")
    ph_number = models.PositiveIntegerField("Phone Number")
    date_created = models.DateTimeField(auto_now_add=True)
    deleted_at = models.DateTimeField(null=True, blank=True)

    class Meta:
        verbose_name = "Accountant"
        verbose_name_plural = "Accountants"

    def __str__(self):
        return "{}".format(self.name)

    def delete_at(self):
        self.deleted_at = timezone.now()
        super().save()


class Subject(models.Model):
    name = models.CharField(max_length=100)
    faculty = models.CharField(max_length=100, choices=FACULTY)
    student = models.ManyToManyField(Student, related_name="subjects")
    teacher = models.ManyToManyField(Teacher, related_name="subjects")
    date_created = models.DateTimeField(auto_now_add=True)
    deleted_at = models.DateTimeField(null=True, blank=True)

    class Meta:
        verbose_name = "Subject"
        verbose_name_plural = "Subjects"

    def __str__(self):
        return "{}".format(self.name)

    def delete(self):
        self.deleted_at = timezone.now()
        super().save()

class Admin(models.Model):
    name = models.OneToOneField(User, on_delete=models.CASCADE, related_name="admins")
    photo = models.ImageField(upload_to="admin/photo",null=True, blank=True)
    ph_number = models.PositiveIntegerField("Phone Number")
    gender = models.CharField(max_length=100, choices=GENDER)
    age = models.PositiveIntegerField(null=True, blank=True)
    email = models.EmailField(default="abc@gmail.com", null=True, blank=True)
    deleted_at = models.DateTimeField(null=True, blank=True)

    class Meta:
        verbose_name_plural = "Admins"

    def __str__(self):
        return "{}".format(self.name)

    def delete(self):
        self.deleted_at = timezone.now()
        super().save()


class Driver(models.Model):
    name = models.CharField("Driver Name", max_length=100)
    photo = models.ImageField(upload_to="driver/photo",null=True, blank=True)
    age = models.PositiveIntegerField() 
    ph_number = models.PositiveIntegerField("Phone number of driver who used bus")
    gender = models.CharField(max_length=100, choices=GENDER)
    deleted_at = models.DateTimeField(null=True, blank=True)

    class Meta:
        verbose_name = "Driver"
        verbose_name_plural = "Drivers"

    def __str__(self):
        return "{}".format(self.name)

    def delete_at(self):
        self.deleted_at = timezone.now()
        super().save()

college_management_app/forms.py
from msilib.schema import Error
from college_management_app.models import *

from django.contrib.auth.models import User
from django import forms


class RegisterForm(forms.Form):
    username = forms.CharField(widget=forms.TextInput())
    email = forms.CharField(widget=forms.EmailInput())
    password = forms.CharField(widget=forms.PasswordInput())
    confirm_password = forms.CharField(widget=forms.PasswordInput())


    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['username'].widget.attrs.update({
            'class':'form-control',
            'placeholder':'Enter your username'
        })
        for field in self.fields:
            self.fields[field].widget.attrs.update({
                'class':'form-control',
            })

    def clean_username(self):
        uname = self.cleaned_data['username']
        if User.objects.filter(username=uname).exists():
            raise forms.ValidationError('Username Already exists')
        return uname
    
    def clean_mail(self):
        email = self.cleaned_data['email']
        if User.objects.filter(email=email).exists():
            raise forms.ValidationError('Email Already exists')
        return email

    def clean_confirm_password(self):
        pwd = self.cleaned_data['password']
        cf_pwd = self.cleaned_data['confirm_password']

        if pwd != cf_pwd:
            raise forms.ValidationError("Password didn't match")
        return cf_pwd

class LoginForm(forms.Form):
    username = forms.CharField(widget=forms.TextInput())
    password = forms.CharField(widget=forms.PasswordInput())

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['username'].widget.attrs.update({
            'class':'form-control',
            'placeholder':'Enter your username'
        })
        self.fields['password'].widget.attrs.update({
            'class':'form-control',
            'placeholder':'Enter your password'
        })
        
    


class StudentForm(forms.ModelForm):
    class Meta:
        model = Student
        fields = ['name','faculty','address','ph_number','age','gender','photo']

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['name'].widget.attrs.update({
            'class':'form-control',
            'placeholder':'Enter your Name'
        })
        for field in self.fields:
            self.fields[field].widget.attrs.update({
                'class':'form-control',
            })
        self.fields['photo'].widget.attrs.update({
            'class':'form-control',
            'onchange':'loadFile(event)',
        })

    def clean_number(self):
        ph_number = self.cleaned_data['ph_number']
        if len(ph_number) < 10:
            raise forms.ValidationError('Please enter more than 10 number')
        return ph_number

college_management_app/views.py
from django.shortcuts import render, redirect
from django.views.generic import (TemplateView, FormView, CreateView, View, ListView, 
                                UpdateView, DeleteView, DetailView)
from django.urls import reverse_lazy
from django.contrib.messages.views import SuccessMessageMixin
from django.contrib.auth.models import User
from django.contrib.auth import authenticate, login, logout
from django.http import JsonResponse, QueryDict
from django.db.models import Q
from django.shortcuts import get_object_or_404

from college_management_app.filters import StudentFilter
from college_management_app.models import *
from college_management_app.forms import RegisterForm, LoginForm, StudentForm

#class based views

#Login required mixins
class LoginRequiredMixin(object):
    def dispatch(self, request, *args, **kwargs):
        user = self.request.user
        if user.is_authenticated:
            pass
        else:
            return redirect('college_management_app:login-page')
        return super().dispatch(request, *args, **kwargs)
    


class HomePage(TemplateView):
    template_name = "college/index.html"

class DashboardPage(LoginRequiredMixin,TemplateView):
    template_name = "dashboard/base.html"

class RegisterPage(SuccessMessageMixin,FormView):
    template_name = "registration/register.html"
    form_class = RegisterForm
    success_url = reverse_lazy('college_management_app:register-page')
    success_message = "Register Successfully"

    def form_valid(self, form):
        uname = form.cleaned_data['username']
        email = form.cleaned_data['email']
        pwd = form.cleaned_data['password']
        cf_pwd = form.cleaned_data['confirm_password']

        User.objects.create_user(username=uname, email=email, password=pwd)
        return super().form_valid(form)

    def get_success_message(self, cleaned_data):
        return self.success_message % cleaned_data

class LoginPage(FormView):
    template_name = "registration/login.html"
    form_class = LoginForm
    success_url = reverse_lazy('college_management_app:login-page')

    def form_valid(self, form):
        uname = form.cleaned_data['username']
        pword = form.cleaned_data['password']

        user = authenticate(username=uname, password=pword)

        if user is not None:
            login(self.request, user)
            print(user,'--------------')
            return redirect('college_management_app:dashboard-page')
        else:
            return render(self.request, self.template_name,{'error':'Username or Password is incorrect','form':form})

        return super().form_valid(form)


class LogoutPage(View):
    def get(self, request):
        logout(request)
        return redirect('college_management_app:login-page')


#Crud Student
class StudentList(ListView):
    template_name = 'student/list.html'
    model = Student
    context_object_name = 'student_list'
    paginate_by = 2

    #search query
    def get_queryset(self):
        query = self.request.GET.get('q')
        object_list = self.model.objects.all()
        if query:
            object_list = object_list.filter(name__icontains=query)
        return object_list


class StudentCreate(LoginRequiredMixin,SuccessMessageMixin,CreateView):
    template_name = "student/add.html"
    form_class = StudentForm
    success_url = reverse_lazy('college_management_app:student-create')
    success_message = "Student Register Successful"

    def form_valid(self, form):
        form.save()
        return super().form_valid(form)

    def get_success_message(self,cleaned_data):
        return self.success_message % cleaned_data

class StudentEdit(LoginRequiredMixin,SuccessMessageMixin,UpdateView):
    template_name = 'student/edit.html'
    form_class = StudentForm
    success_url = reverse_lazy('college_management_app:student-list')
    success_message = "Student Update Successful"


    def get_object(self, **kwargs):
        id = self.kwargs.get('id')
        return get_object_or_404(Student, id=id)

    def form_valid(self, form):
        form.save()
        return super().form_valid(form)

    def get_success_message(self, cleaned_data):
        return self.success_message % cleaned_data

class StudentDelete(LoginRequiredMixin,SuccessMessageMixin,DeleteView):
    template_name = 'student/delete.html'
    model = Student
    success_url = reverse_lazy("college_management_app:student-list")
    success_message = "Student information is deleted"

    def get_object(self, **kwargs):
        id = self.kwargs.get('id')
        return get_object_or_404(Student, id=id)

    def get_success_message(self, cleaned_data):
        return self.success_message % cleaned_data

college_management_app/templates/dashboard/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Dashboard</title>

    <!-- Custom fonts for this template-->
    <link href="vendor/fontawesome-free/css/all.min.css" rel="stylesheet" type="text/css">
    <link href="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/css/select2.min.css" rel="stylesheet" />
    <link
        href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i"
        rel="stylesheet">

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">

    <!-- Custom styles for this template-->
    <link href="{% static 'css/sb-admin-2.min.css' %}" rel="stylesheet">
    {% block css %}

    {% endblock css %}

</head>

<body id="page-top">

    <!-- Page Wrapper -->
    <div id="wrapper">

        <!-- Sidebar -->
        <ul class="navbar-nav bg-gradient-primary sidebar sidebar-dark accordion" id="accordionSidebar">

            <!-- Sidebar - Brand -->
            <a class="sidebar-brand d-flex align-items-center justify-content-center" href="index.html">
                <div class="sidebar-brand-icon rotate-n-15">
                    <i class="fas fa-laugh-wink"></i>
                </div>
                <div class="sidebar-brand-text mx-3">SB Admin <sup>2</sup></div>
            </a>

            <!-- Divider -->
            <hr class="sidebar-divider my-0">

            <!-- Nav Item - Dashboard -->
            <li class="nav-item active">
                <a class="nav-link" href="/">
                    <i class="fas fa-fw fa-tachometer-alt"></i>
                    <span>Dashboard</span></a>
            </li>

            <!-- Divider -->
            <hr class="sidebar-divider">

            <!-- Heading -->
            <div class="sidebar-heading">
                Interface
            </div>

            <!-- Nav Item - Pages Collapse Menu -->
            <li class="nav-item">
                
                {% include 'dashboard/sidebar.html' %}
            </li>

            <!-- Nav Item - Utilities Collapse Menu -->

            <!-- Divider -->

            <!-- Sidebar Message -->

        </ul>
        <!-- End of Sidebar -->

        <!-- Content Wrapper -->
        <div id="content-wrapper" class="d-flex flex-column">

            <!-- Main Content -->
            <div id="content">

                <!-- Topbar -->
                <nav class="navbar navbar-expand navbar-light bg-white topbar mb-4 static-top shadow">

                    <!-- Sidebar Toggle (Topbar) -->
                    <button id="sidebarToggleTop" class="btn btn-link d-md-none rounded-circle mr-3">
                        <i class="fa fa-bars"></i>
                    </button>

                    <!-- Topbar Search -->
    
                    <!-- Topbar Navbar -->
                    <ul class="navbar-nav ml-auto">

                        <!-- Nav Item - Search Dropdown (Visible Only XS) -->
                        <!-- Nav Item - Messages -->
                        <!-- Nav Item - User Information -->
                            

                            {% include 'dashboard/navitem.html' %}

                    </ul>

                </nav>
                <!-- End of Topbar -->

                <!-- Begin Page Content -->
                {% block content %}
                {% endblock content %}
               
                <!-- /.container-fluid -->

            </div>
            <!-- End of Main Content -->

            <!-- Footer -->
            <footer class="sticky-footer bg-white">
                
                {% include 'dashboard/footer.html' %}
            </footer>
            <!-- End of Footer -->

        </div>
        <!-- End of Content Wrapper -->

    </div>
    <!-- End of Page Wrapper -->

    <!-- Scroll to Top Button-->
    <a class="scroll-to-top rounded" href="#page-top">
        <i class="fas fa-angle-up"></i>
    </a>

    <!-- Logout Modal-->
    <div class="modal fade" id="logoutModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel"
        aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLabel">Ready to Leave?</h5>
                    <button class="close" type="button" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">×</span>
                    </button>
                </div>
                <div class="modal-body">Select "Logout" below if you are ready to end your current session.</div>
                <div class="modal-footer">
                    <button class="btn btn-secondary" type="button" data-dismiss="modal">Cancel</button>
                    <a class="btn btn-primary" href="{% url 'college_management_app:login-page' %}">Logout</a>
                </div>
            </div>
        </div>
    </div>

    <!-- Bootstrap core JavaScript-->
    <script src="{% static 'vendor/jquery/jquery.min.js' %}"></script>
    <script src="{% static 'vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>

    <!-- Core plugin JavaScript-->
    <script src="{% static 'vendor/jquery-easing/jquery.easing.min.js' %}"></script>

    <!-- Custom scripts for all pages-->
    <script src="{% static 'js/sb-admin-2.min.js' %}"></script>

    <!-- Page level plugins -->
    <script src="{% static 'vendor/chart.js/Chart.min.js' %}"></script>

    <!-- Page level custom scripts -->
    <script src="{% static 'js/demo/chart-area-demo.js' %}"></script>
    <script src="{% static 'js/demo/chart-pie-demo.js' %}"></script>
    <script src="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/js/select2.min.js"></script>

    <script src="https://unpkg.com/sweetalert/dist/sweetalert.min.js"></script>
    <script>
        {% for message in messages %}
            swal('{{ message }}');
        {% endfor %}
    </script>

    {% block scripts %}
    {% endblock scripts %}

</body>

</html>

college_management_app/templates/dashboard/footer.html
<div class="container my-auto">
    <div class="copyright text-center my-auto">
        <span>Copyright &copy; Your Website 2021</span>
    </div>
</div>

college_management_app/templates/dashboard/navitem.html
{% block content %}
<div class="container">
    <div class="row justify-content-end">
        {% if request.user.is_authenticated %}
            <a href="{% url 'college_management_app:logout-page' %}"> {{ user.username }} </a>
        {% endif %}
    </div>
</div>
{% endblock content %}  

college_management_app/templates/dashboard/sidebar.html
<a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#collapseTwo" aria-expanded="true"
    aria-controls="collapseTwo">
    <span>Student</span>
</a>
<div id="collapseTwo" class="collapse" aria-labelledby="headingTwo" data-parent="#accordionSidebar">
    <div class="bg-white py-2 collapse-inner rounded">
        <a class="collapse-item" href="{% url 'college_management_app:student-create' %}">Add Student </a>
        <a class="collapse-item" href="{% url 'college_management_app:student-list' %}">List Student</a> 
    </div>
</div>

<a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#collapseUtilities" aria-expanded="true"
    aria-controls="collapseUtilities">
    <i class="fas fa-fw fa-wrench"></i>
    <span>Teacher</span>
</a>
<div id="collapseUtilities" class="collapse" aria-labelledby="headingUtilities" data-parent="#accordionSidebar">
    <div class="bg-white py-2 collapse-inner rounded">
        <h6 class="collapse-header">Custom Utilities:</h6>
        <a class="collapse-item" href="utilities-color.html">Colors</a>
        <a class="collapse-item" href="utilities-border.html">Borders</a>
        <a class="collapse-item" href="utilities-animation.html">Animations</a>
        <a class="collapse-item" href="utilities-other.html">Other</a>
    </div>
</div>